spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel360?serverTimezone=Europe/Warsaw
    driverClassName: com.mysql.cj.jdbc.Driver
    username: sda
    password: sda
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update