spring:
  profiles:
    active: dev
#APPLICATION
application:
  weather:
    apiUrl: http://api.weatherapi.com/v1
    apiCurrentPath: /current.json?key={key}&q={q}
    apiKey: d8ff71348e7c42d6918182014200708

# ACTUATOR INFO
info:
  app:
    name: @project.name@
    version: @project.version@
    profile: ${spring.profiles.active}
  serverInfo:
    os: ${os.name}
management:
  endpoints:
    web:
      exposure:
        include: '*'