spring:
  datasource:
    url: jdbc:mysql://rm219172-001.dbaas.ovh.net:35761/travel360?serverTimezone=Europe/Warsaw
    driverClassName: com.mysql.cj.jdbc.Driver
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none