spring:
  profiles:
    active: dev
# ACTUATOR INFO
info:
  app:
    name: @project.name@
    version: @project.version@
    profile: ${spring.profiles.active}
  serverInfo:
    os: ${os.name}
management:
  endpoints:
    web:
      exposure:
        include: '*'